In [1]:
#IMPORTING LIBRARIES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#IGNORE HARMLESS WARNINGS
import warnings
warnings.filterwarnings("ignore")
#SET TO DISPLAY AALL COLUMNS IN DATA SET
pd.set_option("display.max_columns",None)
import pandasql as psql

In [2]:
co2=pd.read_csv(r"C:\Users\R Sobha Supriya\Desktop\internship datsets&files\MY2021_Fuel_Consumption_Ratings.csv",header=0)
co2_bk=co2.copy()
co2.head()

,Year,Make,Model,Vehicle_Class,Engine_Size,Cylinders,Transmission,Fuel_Type,Fuel_Consumption_city,Fuel_Consumption_Hwy,Fuel_Consumption_Comb,Fuel_Consumption_Comb_MPG,CO2_Emissions,CO2_Rating,Smog_Rating
0,2021,Acura,ILX,Compact,2.4,4,AM8,Z,9.9,7.0,8.6,33,199,6,3
1,2021,Acura,NSX,Two-seater,3.5,6,AM9,Z,11.1,10.8,11.0,26,256,4,3
2,2021,Acura,RDX SH-AWD,SUV: Small,2.0,4,AS10,Z,11.0,8.6,9.9,29,232,5,6
3,2021,Acura,RDX SH-AWD A-SPEC,SUV: Small,2.0,4,AS10,Z,11.3,9.1,10.3,27,242,5,6
4,2021,Acura,TLX SH-AWD,Compact,2.0,4,AS10,Z,11.2,8.0,9.8,29,230,5,7

In [3]:
co2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 883 entries, 0 to 882
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       883 non-null    int64
 1   Make                       883 non-null    object
 2   Model                      883 non-null    object
 3   Vehicle_Class              883 non-null    object
 4   Engine_Size                883 non-null    float64
 5   Cylinders                  883 non-null    int64
 6   Transmission               883 non-null    object
 7   Fuel_Type                  883 non-null    object
 8   Fuel_Consumption_city      883 non-null    float64
 9   Fuel_Consumption_Hwy       883 non-null    float64
 10  Fuel_Consumption_Comb      883 non-null    float64
 11  Fuel_Consumption_Comb_MPG  883 non-null    int64
 12  CO2_Emissions              883 non-null    int64
 13  CO2_Rating                 883 non-null    int64
 14  Smog_Rating                883 non-null    int64
dtypes: float64(4), int64(6), object(5)
memory usage: 103.6+ KB

In [4]:
co2.shape

(883, 15)

In [5]:
#checking duplicate values
co2.duplicated().any()

False

In [6]:
#identify missing values
co2.isnull().sum()

Year                         0
Make                         0
Model                        0
Vehicle_Class                0
Engine_Size                  0
Cylinders                    0
Transmission                 0
Fuel_Type                    0
Fuel_Consumption_city        0
Fuel_Consumption_Hwy         0
Fuel_Consumption_Comb        0
Fuel_Consumption_Comb_MPG    0
CO2_Emissions                0
CO2_Rating                   0
Smog_Rating                  0
dtype: int64

In [7]:
co2.columns

Index(['Year', 'Make', 'Model', 'Vehicle_Class', 'Engine_Size', 'Cylinders',
       'Transmission', 'Fuel_Type', 'Fuel_Consumption_city',
       'Fuel_Consumption_Hwy', 'Fuel_Consumption_Comb',
       'Fuel_Consumption_Comb_MPG', 'CO2_Emissions', 'CO2_Rating',
       'Smog_Rating'],
      dtype='object')

In [8]:
co2=co2.drop(['Year','Make','Model','Vehicle_Class','Transmission','Fuel_Type','CO2_Rating' ,'Smog_Rating' ],axis=1)
co2.head()

,Engine_Size,Cylinders,Fuel_Consumption_city,Fuel_Consumption_Hwy,Fuel_Consumption_Comb,Fuel_Consumption_Comb_MPG,CO2_Emissions
0,2.4,4,9.9,7.0,8.6,33,199
1,3.5,6,11.1,10.8,11.0,26,256
2,2.0,4,11.0,8.6,9.9,29,232
3,2.0,4,11.3,9.1,10.3,27,242
4,2.0,4,11.2,8.0,9.8,29,230

In [9]:
#display descriptive STAISTICS
co2.describe()

,Engine_Size,Cylinders,Fuel_Consumption_city,Fuel_Consumption_Hwy,Fuel_Consumption_Comb,Fuel_Consumption_Comb_MPG,CO2_Emissions
count,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000
mean,3.150396,5.652322,12.346206,9.154587,10.908041,27.722537,255.138165
std,1.361575,1.984139,3.494001,2.156966,2.852077,7.761687,64.282038
min,1.000000,3.000000,4.000000,3.900000,4.000000,11.000000,94.000000
25%,2.000000,4.000000,10.100000,7.600000,9.000000,22.000000,210.000000
50%,3.000000,6.000000,11.900000,8.900000,10.500000,27.000000,250.000000
75%,4.000000,6.000000,14.400000,10.400000,12.600000,31.000000,294.000000
max,8.000000,16.000000,30.300000,20.900000,26.100000,71.000000,608.000000

In [10]:
#NO COLS can be declared  AS IT USWED FOR ENTIRE Data
#Identify the independent and Target (dependent) variable
IndepVar = []
for col in co2.columns:
    if col != 'CO2_Emissions':
        IndepVar.append(col)

TargetVar = 'CO2_Emissions'
x = co2[IndepVar]
y = co2[TargetVar]

In [11]:
# Split the data into train and test (random sampling)

from sklearn.model_selection import train_test_split 

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

# Display the shape for train & test data

x_train.shape, x_test.shape, y_train.shape, y_test.shape

((618, 6), (265, 6), (618,), (265,))

In [12]:
# Scaling the features by using MinMaxScaler

from sklearn.preprocessing import MinMaxScaler

mmscaler = MinMaxScaler(feature_range=(0, 1))

#x_train[cols]= mmscaler.fit_transform(x_train[cols])
x_train= mmscaler.fit_transform(x_train)
x_train = pd.DataFrame(x_train)

#x_test[cols]= mmscaler.fit_transform(x_test[cols])
x_test = mmscaler.fit_transform(x_test)

x_test = pd.DataFrame(x_test)

In [13]:
#multiple regression
# Build the multi regression model

from sklearn.linear_model import LinearRegression  

# Create object for the model

ModelMLR = LinearRegression()

# Train the model with training data

ModelMLR.fit(x_train, y_train)

# Predict the model with test dataset

y_pred = ModelMLR.predict(x_test)

# Evaluation metrics for Regression analysis

from sklearn import metrics
print('Mean Absolute Error (MAE):', round(metrics.mean_absolute_error(y_test, y_pred),3))  
print('Mean Squared Error (MSE):', round(metrics.mean_squared_error(y_test, y_pred),3))  
print('Root Mean Squared Error (RMSE):', round(np.sqrt(metrics.mean_squared_error(y_test, y_pred)),3))
print('R2_score:', round(metrics.r2_score(y_test, y_pred),6))
print('Root Mean Squared Log Error (RMSLE):', round(np.log(np.sqrt(metrics.mean_squared_error(y_test, y_pred))),3))
print('Mean Absolute Percentage Error (MAPE):', round(metrics.mean_absolute_percentage_error(y_test, y_pred)*100,3), '%')
# Define the function to calculate the MAPE - Mean Absolute Percentage Error

def MAPE (y_test, y_pred): 
    y_test, y_pred = np.array(y_test), np.array(y_pred)
    return np.mean(np.abs((y_test - y_pred) / y_test)) * 100

# Evaluation of MAPE
result = MAPE(y_test, y_pred)
print('Mean Absolute Percentage Error (MAPE):', round(result, 3), '%')

# Calculate Adjusted R squared values 

r_squared = round(metrics.r2_score(y_test, y_pred),6)
adjusted_r_squared = round(1 - (1-r_squared)*(len(y)-1)/(len(y)-x.shape[1]-1),6)
print('Adj R Square: ', adjusted_r_squared)

Mean Absolute Error (MAE): 28.879
Mean Squared Error (MSE): 1445.051
Root Mean Squared Error (RMSE): 38.014
R2_score: 0.586325
Root Mean Squared Log Error (RMSLE): 3.638
Mean Absolute Percentage Error (MAPE): 10.726 %
Mean Absolute Percentage Error (MAPE): 10.726 %
Adj R Square:  0.583492

In [14]:
#display the final results 
Results = pd.DataFrame({'CO2_Emissions_A':y_test, 'CO2_Emissions_P_F':y_pred})
#Merge two Dataframes on index of both the dataframes
ResultsFinal = co2_bk.merge(Results,left_index=True,right_index=True)
# Calculate the %of Error
#ResultsFinal['%Error'] = round(((ResultsFinal['CSinMPa_A']-ResultsFinal['CSinMPa_P'])/ResultsFinal['CSinMPa_A'])*100,3)
#display 10 records randomly
ResultsFinal.sample(10)

,Year,Make,Model,Vehicle_Class,Engine_Size,Cylinders,Transmission,Fuel_Type,Fuel_Consumption_city,Fuel_Consumption_Hwy,Fuel_Consumption_Comb,Fuel_Consumption_Comb_MPG,CO2_Emissions,CO2_Rating,Smog_Rating,CO2_Emissions_A,CO2_Emissions_P_F
54,2021,Audi,SQ5 Sportback quattro,SUV: Small,3.0,6,AS8,Z,13.1,9.9,11.6,24,274,4,5,274,302.001766
786,2021,Rolls-Royce,Phantom EWB,Full-size,6.7,12,AS8,Z,20.0,11.8,16.3,17,382,1,3,382,455.386733
593,2021,Mercedes-Benz,AMG C 63 S Sedan,Compact,4.0,8,A9,Z,13.5,8.9,11.4,25,269,4,3,269,310.366883
259,2021,Ford,Bronco Sport 4WD,SUV: Small,2.0,4,AS8,X,11.1,8.9,10.1,28,238,5,5,238,254.087051
814,2021,Toyota,Camry TRD,Mid-size,3.5,6,AS8,X,10.8,7.6,9.4,30,220,5,5,220,250.870640
168,2021,Chevrolet,Colorado,Pickup truck: Small,2.5,4,A6,X,12.2,9.4,10.9,26,257,4,6,257,274.545390
192,2021,Chevrolet,Silverado 4WD Custom/WT,Pickup truck: Standard,2.7,4,A8,X,12.5,10.8,11.7,24,275,4,6,275,292.738105
344,2021,GMC,Sierra,Pickup truck: Standard,3.0,6,A10,D,10.2,7.8,9.1,31,245,5,3,245,239.019658
254,2021,Dodge,Durango AWD,SUV: Standard,5.7,8,A8,X,16.7,10.9,14.1,20,331,3,5,331,380.652784
528,2021,Lexus,RC 350 AWD,Subcompact,3.5,6,AS6,Z,12.2,9.0,10.8,26,253,4,5,253,286.184667

In [15]:
#compare classification algorithms
#load the results
RGRResults=pd.read_csv(r"C:\Users\R Sobha Supriya\Desktop\internship datsets&files\RGRResults.csv",header=0)
#display first 5 records
RGRResults.head()

Empty DataFrame
Columns: [Model Name, Mean_Absolute_Error_MAE, Adj_R_Square, Root_Mean_Squared_Error_RMSE, Mean_Absolute_Percentage_Error_MAPE, Mean_Squared_Error_MSE, Root_Mean_Squared_Log_Error_RMSLE, R2_score]
Index: []

In [16]:
# Build the Regression / Regressor models

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import ExtraTreesRegressor
#from sklearn.neighbors import KNeighborsRegressor
#from sklearn.linear_model import BayesianRidge
#from sklearn.svm import SVR

# Create objects of Regression / Regressor models with default hyper-parameters

ModelMLR = LinearRegression()
ModelDCR = DecisionTreeRegressor()
ModelRFR = RandomForestRegressor()
ModelETR = ExtraTreesRegressor()
#ModelKNN = KNeighborsRegressor(n_neighbors=5)
#ModelBRR = BayesianRidge()
#ModelSVR = SVR()

# Evalution matrix for all the algorithms

#MM = [ModelMLR, ModelDCR, ModelRFR, ModelETR, ModelKNN, ModelBRR, ModelSVR] 
MM = [ModelMLR, ModelDCR, ModelRFR, ModelETR]

for models in MM:
    
    # Fit the model with train data
    
    models.fit(x_train, y_train)
    
    # Predict the model with test data

    y_pred = models.predict(x_test)
    
    # Print the model name
    
    print('Model Name: ', models)
    
    # Evaluation metrics for Regression analysis

    from sklearn import metrics

    print('Mean Absolute Error (MAE):', round(metrics.mean_absolute_error(y_test, y_pred),3))  
    print('Mean Squared Error (MSE):', round(metrics.mean_squared_error(y_test, y_pred),3))  
    print('Root Mean Squared Error (RMSE):', round(np.sqrt(metrics.mean_squared_error(y_test, y_pred)),3))
    print('R2_score:', round(metrics.r2_score(y_test, y_pred),6))
    print('Root Mean Squared Log Error (RMSLE):', round(np.log(np.sqrt(metrics.mean_squared_error(y_test, y_pred))),3))
    
    # Define the function to calculate the MAPE - Mean Absolute Percentage Error

    def MAPE (y_test, y_pred):
        y_test, y_pred = np.array(y_test), np.array(y_pred)
        return np.mean(np.abs((y_test - y_pred) / y_test)) * 100
    
    # Evaluation of MAPE 

    result = MAPE(y_test, y_pred)
    print('Mean Absolute Percentage Error (MAPE):', round(result, 2), '%')
    
    # Calculate Adjusted R squared values 

    r_squared = round(metrics.r2_score(y_test, y_pred),6)
    adjusted_r_squared = round(1 - (1-r_squared)*(len(y)-1)/(len(y)-x.shape[1]-1),6)
    print('Adj R Square: ', adjusted_r_squared)
    print('------------------------------------------------------------------------------------------------------------')
    #-------------------------------------------------------------------------------------------
    new_row = {'Model Name' : models,
               'Mean_Absolute_Error_MAE' : metrics.mean_absolute_error(y_test, y_pred),
               'Adj_R_Square' : adjusted_r_squared,
               'Root_Mean_Squared_Error_RMSE' : np.sqrt(metrics.mean_squared_error(y_test, y_pred)),
               'Mean_Absolute_Percentage_Error_MAPE' : result,
               'Mean_Squared_Error_MSE' : metrics.mean_squared_error(y_test, y_pred),
               'Root_Mean_Squared_Log_Error_RMSLE': np.log(np.sqrt(metrics.mean_squared_error(y_test, y_pred))),
               'R2_score' : metrics.r2_score(y_test, y_pred)}
    RGRResults = RGRResults.append(new_row, ignore_index=True)
    #-------------------------------------------------------------------------------------------

Model Name:  LinearRegression()
Mean Absolute Error (MAE): 28.879
Mean Squared Error (MSE): 1445.051
Root Mean Squared Error (RMSE): 38.014
R2_score: 0.586325
Root Mean Squared Log Error (RMSLE): 3.638
Mean Absolute Percentage Error (MAPE): 10.73 %
Adj R Square:  0.583492
------------------------------------------------------------------------------------------------------------
Model Name:  DecisionTreeRegressor()
Mean Absolute Error (MAE): 23.097
Mean Squared Error (MSE): 1165.949
Root Mean Squared Error (RMSE): 34.146
R2_score: 0.666224
Root Mean Squared Log Error (RMSLE): 3.531
Mean Absolute Percentage Error (MAPE): 8.29 %
Adj R Square:  0.663938
------------------------------------------------------------------------------------------------------------
Model Name:  RandomForestRegressor()
Mean Absolute Error (MAE): 22.163
Mean Squared Error (MSE): 918.899
Root Mean Squared Error (RMSE): 30.313
R2_score: 0.736947
Root Mean Squared Log Error (RMSLE): 3.412
Mean Absolute Percentage Error (MAPE): 8.24 %
Adj R Square:  0.735145
------------------------------------------------------------------------------------------------------------
Model Name:  ExtraTreesRegressor()
Mean Absolute Error (MAE): 18.308
Mean Squared Error (MSE): 848.082
Root Mean Squared Error (RMSE): 29.122
R2_score: 0.75722
Root Mean Squared Log Error (RMSLE): 3.371
Mean Absolute Percentage Error (MAPE): 6.66 %
Adj R Square:  0.755557
------------------------------------------------------------------------------------------------------------

In [17]:
RGRResults.head()

,Model Name,Mean_Absolute_Error_MAE,Adj_R_Square,Root_Mean_Squared_Error_RMSE,Mean_Absolute_Percentage_Error_MAPE,Mean_Squared_Error_MSE,Root_Mean_Squared_Log_Error_RMSLE,R2_score
0,LinearRegression(),28.879244,0.583492,38.013833,10.726300,1445.051468,3.637950,0.586325
1,DecisionTreeRegressor(),23.097484,0.663938,34.145989,8.287886,1165.948532,3.530645,0.666224
2,"(DecisionTreeRegressor(max_features=1.0, rando...",22.163392,0.735145,30.313351,8.235497,918.899259,3.411588,0.736947
3,"(ExtraTreeRegressor(random_state=1431166513), ...",18.307723,0.755557,29.121848,6.662327,848.082045,3.371489,0.757220

In [18]:
y_predF=ModelETR.predict(x_test)

In [19]:
# Calculate the %of Error

ResultsFinal['%Error'] = round(((ResultsFinal['CO2_Emissions_A']-ResultsFinal['CO2_Emissions_P_F'])/ResultsFinal['CO2_Emissions_A'])*100,3)

In [20]:
ResultsFinal.sample(5)

,Year,Make,Model,Vehicle_Class,Engine_Size,Cylinders,Transmission,Fuel_Type,Fuel_Consumption_city,Fuel_Consumption_Hwy,Fuel_Consumption_Comb,Fuel_Consumption_Comb_MPG,CO2_Emissions,CO2_Rating,Smog_Rating,CO2_Emissions_A,CO2_Emissions_P_F,%Error
266,2021,Ford,Escape,SUV: Small,1.5,3,A8,X,8.5,6.8,7.8,36,182,6,7,182,190.844428,-4.860
172,2021,Chevrolet,Colorado 4WD,Pickup truck: Small,2.8,4,A6,D,12.2,8.4,10.5,27,294,3,3,294,268.540979,8.660
199,2021,Chevrolet,Silverado 4WD FFV,Pickup truck: Standard,5.3,8,A6,E,22.0,16.4,19.5,14,326,3,3,326,504.895533,-54.876
281,2021,Ford,F-150 FFV,Pickup truck: Standard,5.0,8,AS10,X,14.0,10.0,12.2,23,287,3,5,287,331.237529,-15.414
833,2021,Toyota,Highlander AWD,SUV: Small,3.5,6,AS8,X,11.8,8.6,10.3,27,241,5,5,241,270.637076,-12.298